@startuml
title 城市组织中心-用户管理时序图

actor 组织管理员用户 as user
participant "用户管理" as userAdmin
participant "易信用户中心" as YXAdmin
participant "日志管理" as LogAdmin

autonumber
user->userAdmin:创建用户信息
userAdmin->YXAdmin:调用易信用户中心接口创建用户
YXAdmin-->userAdmin:返回易信创建的用户信息
userAdmin->userAdmin:城市组织中心创建用户
userAdmin->LogAdmin:记录用户创建的日志信息
LogAdmin-->user:返回用户创建信息
user->userAdmin:编辑用户信息
userAdmin->LogAdmin:记录用户变更的日志信息
LogAdmin-->user:返回用户变更信息
user->userAdmin:注销用户信息
userAdmin->LogAdmin:记录用户注销的日志信息
LogAdmin-->user:返回用户注销信息
@enduml